### ISSUE TITLE
Errors occurred when trying structure learning examples in Python 3

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy_notebook#18]
I'm using Python3 to try the following example (originally from [here](https://github.com/pgmpy/pgmpy_notebook/blob/master/notebooks/Learning%20Bayesian%20Networks%20from%20Data.ipynb)):

```py
import pandas as pd
import numpy as np
from pgmpy.estimators import BdeuScore, K2Score, BicScore
from pgmpy.models import BayesianModel

# create random data sample with 3 variables, where Z is dependent on X, Y:
data = pd.DataFrame(np.random.randint(0, 4, size=(5000, 2)), columns=list('XY'))
data['Z'] = data['X'] + data['Y']

bdeu = BdeuScore(data, equivalent_sample_size=5)
k2 = K2Score(data)
bic = BicScore(data)

model1 = BayesianModel([('X', 'Z'), ('Y', 'Z')])  # X -> Z <- Y
model2 = BayesianModel([('X', 'Z'), ('X', 'Y')])  # Y <- X -> Z
```

The errors occurred:
```
Traceback (most recent call last):
  File "try_crf.py", line 68, in <module>
    print(bdeu.score(model1))
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/estimators/StructureScore.py", line 70, in score
    score += self.local_score(node, model.predecessors(node))
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/estimators/BdeuScore.py", line 53, in local_score
    state_counts = self.state_counts(variable, parents)
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/estimators/base.py", line 117, in state_counts
    state_count_data = data.groupby([variable] + parents).size().unstack(parents)
TypeError: can only concatenate list (not "dict_keyiterator") to list
```

I guess this is not a big issue --- just convert `dict_keyiterator` to a `list` in the source code. For example, in the source code
```
/usr/local/lib/python3.5/site-packages/pgmpy-0.1.3-py3.5.egg/pgmpy/estimators/base.py
```
at the beginning of function `state_counts`, add
```
parents = list(parents)
```
It'll be fixed.

Thanks!

-----------

Darwin-16.3.0-x86_64-i386-64bit
Python 3.5.2 (default, Aug 16 2016, 05:35:40) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
NumPy 1.13.0
SciPy 0.19.0
Scikit-Learn 0.18
pgmpy 0.1.3

**Comment by ankurankan** [comment]
@mrholiday Thanks for reporting this and sorry for my late reply. This has been fixed now.

**Comment by ghost** [comment]
@ankurankan: It seems that his error has not been fixed. If I run:
`print(k2.score(model1))`
after the code of @mrholiday, I still have the same error.

The error has been solved in one place only.

**Comment by ankurankan** [comment]
@moakra This works fine for me:

```python
In [1]: import pandas as pd
   ...: import numpy as np
   ...: from pgmpy.estimators import BdeuScore, K2Score, BicScore
   ...: from pgmpy.models import BayesianModel
   ...: 
   ...: # create random data sample with 3 variables, where Z is dependent on X, Y:
   ...: data = pd.DataFrame(np.random.randint(0, 4, size=(5000, 2)), columns=list('XY'))
   ...: data['Z'] = data['X'] + data['Y']
   ...: 
   ...: bdeu = BdeuScore(data, equivalent_sample_size=5)
   ...: k2 = K2Score(data)
   ...: bic = BicScore(data)
   ...: 
   ...: model1 = BayesianModel([('X', 'Z'), ('Y', 'Z')])  # X -> Z <- Y
   ...: model2 = BayesianModel([('X', 'Z'), ('X', 'Y')])  # Y <- X -> Z
   ...: 
   ...: 

In [2]: print(k2.score(model1))
-14329.034082786358
```
By any chance are you using the latest version of networkx ? If yes, downgrading it to 0.11 should fix this.

**Comment by rbankosegger** [comment]
I had the same error as @mrholiday, but was able to fix it with @ankurankan's tip. I had `networkx 2.3` installed. Reverting to `networkx 1.11` fixed the problem for me.

@ankurankan, given that this issues till seems to be around, maybe it's an idea to reopen this ticket?

**Comment by ankurankan** [comment]
@rbankosegger This has been fixed in the latest dev branch and should work with the latest networkx.

**Comment by nfoerster** [comment]
Yea but there are inconsistencies now, because plotting the BN shown below needs a higher version:

 ```python
import networkx as nx
import pylab as plt
nx.draw(model, with_labels=True)
plt.show()

AttributeError: module 'matplotlib.pyplot' has no attribute 'ishold'`

**Comment by ankurankan** [comment]
@Thorgas1988 Plotting seems to be working fine on my system with python=3.6, networkx=2.2, and matplotlib=3.0.3. Could you please share your versions so that I can reproduce the error?

**Comment by nfoerster** [comment]
Yea it works with networkx 2.2 but pgmpy seems not to work with that version, it downgrades networkx accordingly:
 ```bash
(louvier) C:\WINDOWS\system32>pip install networkx==2.2
Collecting networkx==2.2
  Downloading https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip (1.7MB)
    100% |████████████████████████████████| 1.7MB 360kB/s
Requirement already satisfied: decorator>=4.3.0 in c:\programdata\miniconda3\envs\louvier\lib\site-packages (from networkx==2.2) (4.4.0)
Building wheels for collected packages: networkx
  Building wheel for networkx (setup.py) ... done
  Stored in directory: C:\Users\fn2734\AppData\Local\pip\Cache\wheels\68\f8\29\b53346a112a07d30a5a84d53f19aeadaa1a474897c0423af91
Successfully built networkx
pgmpy 0.1.7 has requirement networkx<1.12,>=1.11, but you'll have networkx 2.2 which is incompatible.
Installing collected packages: networkx
  Found existing installation: networkx 1.11
    Uninstalling networkx-1.11:
      Successfully uninstalled networkx-1.11
Successfully installed networkx-2.2

(louvier) C:\WINDOWS\system32>pip install pgmpy
Requirement already satisfied: pgmpy in c:\programdata\miniconda3\envs\louvier\lib\site-packages (0.1.7)
Requirement already satisfied: numpy>=1.14.0 in c:\programdata\miniconda3\envs\louvier\lib\site-packages (from pgmpy) (1.16.2)
Requirement already satisfied: scipy>=1.0.0 in c:\programdata\miniconda3\envs\louvier\lib\site-packages (from pgmpy) (1.2.1)
Collecting networkx<1.12,>=1.11 (from pgmpy)
  Using cached https://files.pythonhosted.org/packages/d3/2c/e473e54afc9fae58dfa97066ef6709a7e35a1dd1c28c5a3842989322be00/networkx-1.11-py2.py3-none-any.whl
Requirement already satisfied: decorator>=3.4.0 in c:\programdata\miniconda3\envs\louvier\lib\site-packages (from networkx<1.12,>=1.11->pgmpy) (4.4.0)
Installing collected packages: networkx
  Found existing installation: networkx 2.2
    Uninstalling networkx-2.2:
      Successfully uninstalled networkx-2.2
Successfully installed networkx-1.11
`

**Comment by ankurankan** [comment]
@Thorgas1988 This is happening because the pypi package hasn't been updated. It should be fixed in the next release. If you want to work with the latest networkx, you can just install the `dev` branch from github.
